---
applications:
- guillotina_elasticsearch
- guillotina_rediscache
- guillotina_swagger
- guillotina_dbusers
databases:
- db:
    storage: postgresql
    transaction_strategy: resolve
    cache_strategy: redis
    dsn:
      scheme: postgres
      dbname: guillotina
      user: postgres
      host: postgresql
      password: ''
      port: 5432
    pool_size: 40
    read_only: false
host: 0.0.0.0
port: 8080
root_user:
  password: root
cors:
  allow_origin:
  - "*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
redis:
  host: redis
  port: 6379
  ttl: 3600
  memory_cache_size: 1000
elasticsearch:
  index_name_prefix: guillotina-
  connection_settings:
    endpoints:
    - elasticsearch:9200
    sniffer_timeout: 0.5
